# Generated by Django 5.0.14 on 2025-07-14 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DependenciaRelacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('base', 'Base'), ('referencia', 'Referencia')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=10)),
                ('rol', models.CharField(blank=True, max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('t_objeto', models.CharField(choices=[('Tabla', 'Tabla SQL'), ('Vista', 'Vista'), ('Funcion', 'Función'), ('Store procedure', 'Store Procedure'), ('Trigger', 'Trigger'), ('Job', 'JOB')], max_length=20)),
                ('f_creacion', models.DateTimeField(auto_now_add=True)),
                ('estatus', models.CharField(choices=[('Activo', 'Activo'), ('Desactivandose', 'Desactivandose'), ('Inactivo', 'Inactivo')], max_length=14)),
                ('descripcion', models.TextField(blank=True)),
                ('dependencias', models.ManyToManyField(blank=True, related_name='referenciado_por', through='tasks.DependenciaRelacion', to='tasks.objeto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetos', to='tasks.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='dependenciarelacion',
            name='desde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_desde', to='tasks.objeto'),
        ),
        migrations.AddField(
            model_name='dependenciarelacion',
            name='hacia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencias_hacia', to='tasks.objeto'),
        ),
    ]
